resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/akoranne/rulesengine.git
    branch: develop

jobs:
- name: package
  public: true
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: package
    file: source-code/ci/pipelines/buildUnit.yml
    
